a=[{"Comarca": "Catalunya ",
  "Departament": "012 Atenci\xc3\xb3 Ciutadana",
  "Depen": "",
  "Nom": "",
  "Poblacio": " Espa\xc3\xb1a",
  "codi": "535",
  "cp": ""},
 {"Comarca": None,
  "Departament": "061 CatSalut Respon",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "3383",
  "cp": None},
 {"Comarca": None,
  "Departament": "900 900 120 Contra la viol\xc3\xa8ncia masclista",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18893",
  "cp": None},
 {"Comarca": None,
  "Departament": "Albergs",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17136",
  "cp": None},
 {"Comarca": None,
  "Departament": "Camps d'Aprenentatge (CdA)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18129",
  "cp": None},
 {"Comarca": None,
  "Departament": "Centre Interdisciplinari de Tecnologia, Innovaci\xc3\xb3 i Educaci\xc3\xb3 per a la Sostenibilitat (Cities) (UPC)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "14555",
  "cp": None},
 {"Comarca": None,
  "Departament": "Centre d'Atenci\xc3\xb3 Prim\xc3\xa0ria (CAP) Aiguafreda",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "14453",
  "cp": None},
 {"Comarca": "Sabadell ",
  "Departament": "Centre d'Atenci\xc3\xb3 Prim\xc3\xa0ria (CAP) Centre (Sabadell)",
  "Depen": "",
  "Nom": "",
  "Poblacio": " Vall\xc3\xa8s Occidental",
  "codi": "7470",
  "cp": ""},
 {"Comarca": None,
  "Departament": "Centre d'Atenci\xc3\xb3 Prim\xc3\xa0ria (CAP) La Ll\xc3\xa1ntia",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17200",
  "cp": None},
 {"Comarca": "Sentmenat ",
  "Departament": "Centre d'Atenci\xc3\xb3 Prim\xc3\xa0ria (CAP) Sentmenat",
  "Depen": "",
  "Nom": "",
  "Poblacio": " Vall\xc3\xa8s Occidental",
  "codi": "12202",
  "cp": ""},
 {"Comarca": None,
  "Departament": "Centre de Desenvolupament Infantil i Atenci\xc3\xb3 Preco\xc3\xa7 (CDIAP) - Barcelona: Dreta de l'Eixample, Sagrada Fam\xc3\xadlia i Fort Pienc (ASPANIAS)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18710",
  "cp": None},
 {"Comarca": None,
  "Departament": "Centre de Desenvolupament Infantil i Atenci\xc3\xb3 Preco\xc3\xa7 (CDIAP) - Vall\xc3\xa8s Oriental",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18737",
  "cp": None},
 {"Comarca": " Maresme",
  "Departament": "Centre de Normalitzaci\xc3\xb3 Ling\xc3\xbc\xc3\xadstica del Maresme (CNL)",
  "Depen": "Matar\xc3\xb3 ",
  "Nom": "",
  "Poblacio": None,
  "codi": "6930",
  "cp": ""},
 {"Comarca": " Baix Llobregat",
  "Departament": "Centre de Recursos Pedag\xc3\xb2gics (CRP) del Baix Llobregat VI",
  "Depen": "",
  "Nom": "",
  "Poblacio": "Sant Vicen\xc3\xa7 dels Horts ",
  "codi": "2059",
  "cp": ""},
 {"Comarca": None,
  "Departament": "Centre de dia per a persones amb discapacitats Tres Pins",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18685",
  "cp": None},
 {"Comarca": "Catalunya ",
  "Departament": "Centres Docents de Catalunya",
  "Depen": "",
  "Nom": "",
  "Poblacio": " Espa\xc3\xb1a",
  "codi": "14552",
  "cp": " Espa\xc3\xb1a"},
 {"Comarca": None,
  "Departament": "Centres educatius de Just\xc3\xadcia Juvenil",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "16831",
  "cp": None},
 {"Comarca": None,
  "Departament": "Centres penitenciaris",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "16829",
  "cp": None},
 {"Comarca": None,
  "Departament": "Comissions d'Assist\xc3\xa8ncia Jur\xc3\xaddica Gratu\xc3\xafta",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "15822",
  "cp": None},
 {"Comarca": None,
  "Departament": "Comissi\xc3\xb3 T\xc3\xa8cnica d'Atenci\xc3\xb3 i Gesti\xc3\xb3 de Trucades d'Urg\xc3\xa8ncia",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "16183",
  "cp": None},
 {"Comarca": None,
  "Departament": "Comissi\xc3\xb3 d'Estudiants",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18146",
  "cp": None},
 {"Comarca": None,
  "Departament": "Comissi\xc3\xb3 de Recerca de l'\xc3\x80mbit Immobiliari",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18043",
  "cp": None},
 {"Comarca": None,
  "Departament": "Comissi\xc3\xb3 de Recerca de l'\xc3\x80mbit de la Sostenibilitat i de la Qualitat de l'Edificaci\xc3\xb3",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18044",
  "cp": None},
 {"Comarca": None,
  "Departament": "Comissi\xc3\xb3 de Recerca de l'\xc3\x80mbit de les Pol\xc3\xadtiques P\xc3\xbabliques de l'Habitatge",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18046",
  "cp": None},
 {"Comarca": None,
  "Departament": "Comissi\xc3\xb3 de Recerca de l'\xc3\x80mbit del Dret a l'Habitatge i de l'Exclusi\xc3\xb3 Social Residencial",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18045",
  "cp": None},
 {"Comarca": None,
  "Departament": "Comit\xc3\xa8 de Recursos Tecnol\xc3\xb2gics i Sistemes d'Informaci\xc3\xb3",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18207",
  "cp": None},
 {"Comarca": None,
  "Departament": "Consell Executiu o Govern",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "15008",
  "cp": None},
 {"Comarca": None,
  "Departament": "Consell de Direcci\xc3\xb3",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "15989",
  "cp": None},
 {"Comarca": None,
  "Departament": "Consell de Pol\xc3\xadtica Industrial de Catalunya",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17466",
  "cp": None},
 {"Comarca": " Barcelona ",
  "Departament": "Consorci Catalan Films &amp",
  "Depen": "\xc3\x80lex Navarro Garrich",
  "Nom": " TV",
  "Poblacio": " Barcelon\xc3\xa8s",
  "codi": "12783",
  "cp": "08021 "},
 {"Comarca": None,
  "Departament": "Coordinador d'\xc3\x80rees",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "16377",
  "cp": None},
 {"Comarca": None,
  "Departament": "Departament de Gesti\xc3\xb3 i Seguiment Econ\xc3\xb2mic",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "16521",
  "cp": None},
 {"Comarca": " Baix Llobregat",
  "Departament": "Equip d'Assessorament i Orientaci\xc3\xb3 Psicopedag\xc3\xb2gica (EAP) B-39 de Sant Vicen\xc3\xa7 Dels Horts",
  "Depen": "",
  "Nom": "",
  "Poblacio": "Sant Vicen\xc3\xa7 dels Horts ",
  "codi": "2150",
  "cp": ""},
 {"Comarca": " Barcelon\xc3\xa8s",
  "Departament": "Equip d'Atenci\xc3\xb3 a la Inf\xc3\xa0ncia i Adolesc\xc3\xa8ncia (EAIA) de Barcelona: Sants-Montju\xc3\xafc (Districte 3)",
  "Depen": "Barcelona ",
  "Nom": "",
  "Poblacio": None,
  "codi": "5297",
  "cp": ""},
 {"Comarca": None,
  "Departament": "Equip de Protecci\xc3\xb3 de la Salut a la Selva Maritima-Alt Maresme (Ag\xc3\xa8ncia de Protecci\xc3\xb3 de la Salut)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17994",
  "cp": None},
 {"Comarca": None,
  "Departament": "Equips d'Assessorament T\xc3\xa8cnic Menors",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17167",
  "cp": None},
 {"Comarca": None,
  "Departament": "Equips d'Assessorament T\xc3\xa8cnic Penal",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17168",
  "cp": None},
 {"Comarca": None,
  "Departament": "Equips de Mediaci\xc3\xb3 i Reparaci\xc3\xb3 Penal ",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17166",
  "cp": None},
 {"Comarca": None,
  "Departament": "Escola Universit\xc3\xa0ria de Fisioter\xc3\xa0pia Garb\xc3\xad (UdG)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "13453",
  "cp": None},
 {"Comarca": None,
  "Departament": "Escola Universit\xc3\xa0ria de Turisme Formatic Barna (UdG)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "16553",
  "cp": None},
 {None: [" Ripoll\xc3\xa8s"],
  "Comarca": " Ripoll ",
  "Departament": "Estaci\xc3\xb3 d'ITV (GI-08) Ripoll\xc3\xa8s",
  "Depen": "",
  "Nom": "Francesc Garcia",
  "Poblacio": " Ripoll\xc3\xa8s",
  "codi": "5761",
  "cp": "17500 "},
 {"Comarca": " Andorra",
  "Departament": "Estudis Virtuals a Andorra (UOC)",
  "Depen": " Sant Juli\xc3\xa0 de L\xc3\xb2ria",
  "Nom": "",
  "Poblacio": " Andorra",
  "codi": "10491",
  "cp": "AD600"},
 {"Comarca": " Alt Empord\xc3\xa0",
  "Departament": "Fundaci\xc3\xb3 Gala-Salvador Dal\xc3\xad",
  "Depen": "",
  "Nom": "",
  "Poblacio": "Figueres ",
  "codi": "2007069",
  "cp": " Alt Empord\xc3\xa0"},
 {"Comarca": None,
  "Departament": "Grup de Treball Sobre Panells de Missatge Variable",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "16008",
  "cp": None},
 {"Comarca": None,
  "Departament": "Informaci\xc3\xb3 General (UOC)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "13629",
  "cp": None},
 {"Comarca": None,
  "Departament": "Informaci\xc3\xb3 Mar\xc3\xadtima (Catalunya R\xc3\xa0dio, SRG, SA)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "7733",
  "cp": None},
 {"Comarca": None,
  "Departament": "Informaci\xc3\xb3 Sobre Donaci\xc3\xb3 d'\xc3\x92rgans",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "3382",
  "cp": None},
 {"Comarca": None,
  "Departament": "Informaci\xc3\xb3 dels Ferrocarrils de la Generalitat de Catalunya",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "4120",
  "cp": None},
 {"Comarca": None,
  "Departament": "Informaci\xc3\xb3 sobre el risc d'allaus",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "4119",
  "cp": None},
 {"Comarca": None,
  "Departament": "Informaci\xc3\xb3 sobre la Xarxa S\xc3\xadsmica",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "4118",
  "cp": None},
 {"Comarca": None,
  "Departament": "Inf\xc3\xa0ncia respon 900 300 777",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "13458",
  "cp": None},
 {"Comarca": None,
  "Departament": "Institucions Col\xc2\xb7laboradores d'Integraci\xc3\xb3 Familiar (ICIF)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17440",
  "cp": None},
 {"Comarca": None,
  "Departament": "Observatori de l'H\xc3\xa0bitat i la Segregaci\xc3\xb3 Urbana",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18036",
  "cp": None},
 {"Comarca": None,
  "Departament": "Oficines d'Atenci\xc3\xb3 a la V\xc3\xadctima del Delicte",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17174",
  "cp": None},
 {"Comarca": None,
  "Departament": "Oficines d'Atenci\xc3\xb3 al Ciutad\xc3\xa0 de l'Administraci\xc3\xb3 de Just\xc3\xadcia",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "15592",
  "cp": None},
 {"Comarca": " Maresme",
  "Departament": "Policia Local de Calella",
  "Depen": "",
  "Nom": "",
  "Poblacio": "Calella ",
  "codi": "17754",
  "cp": ""},
 {"Comarca": " Maresme",
  "Departament": "Policia Local de Sant Pol de Mar",
  "Depen": "",
  "Nom": "",
  "Poblacio": "Sant Pol de Mar",
  "codi": "17877",
  "cp": " Maresme"},
 {"Comarca": " Baix Ebre",
  "Departament": "Policia Local de Tortosa",
  "Depen": "Tortosa ",
  "Nom": "",
  "Poblacio": "Tortosa ",
  "codi": "17913",
  "cp": ""},
 {"Comarca": None,
  "Departament": "Policies Locals a Catalunya",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17716",
  "cp": None},
 {"Comarca": None,
  "Departament": "Programaci\xc3\xb3 de Visites",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "12146",
  "cp": None},
 {"Comarca": " Vall\xc3\xa8s Occidental",
  "Departament": "Punt d'Autoservei a Castellar del Vall\xc3\xa8s",
  "Depen": "",
  "Nom": "",
  "Poblacio": "Castellar del Vall\xc3\xa8s",
  "codi": "18416",
  "cp": ""},
 {"Comarca": " Vall\xc3\xa8s Occidental",
  "Departament": "Punt d'Autoservei a Palau-solit\xc3\xa0 i Plegamans",
  "Depen": "Palau-solit\xc3\xa0 i Plegamans ",
  "Nom": "",
  "Poblacio": None,
  "codi": "18447",
  "cp": ""},
 {"Comarca": " Baix Llobregat",
  "Departament": "Punt d'Autoservei a Pallej\xc3\xa0",
  "Depen": "",
  "Nom": "",
  "Poblacio": "Pallej\xc3\xa0 ",
  "codi": "18448",
  "cp": ""},
 {"Comarca": " Fran\xc3\xa7a",
  "Departament": "Punt de Suport de Perpignan (UOC)",
  "Depen": "",
  "Nom": "",
  "Poblacio": " Perpiny\xc3\xa0",
  "codi": "13873",
  "cp": "F-66000 "},
 {"Comarca": None,
  "Departament": "Resid\xc3\xa8ncia per a disminu\xc3\xafts ps\xc3\xadquics profunds La Pineda",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17512",
  "cp": None},
 {"Comarca": None,
  "Departament": "Resid\xc3\xa8ncia per a persones amb discapacitats Tres Pins",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18686",
  "cp": None},
 {"Comarca": None,
  "Departament": "Resid\xc3\xa8ncies per a persones amb discapacitats",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17486",
  "cp": None},
 {"Comarca": None,
  "Departament": "Responsable de Relacions Institucionals i Participaci\xc3\xb3 a Barcelona",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "16805",
  "cp": None},
 {"Comarca": None,
  "Departament": "S.T. Andorra",
  "Depen": "AD500 ",
  "Nom": "",
  "Poblacio": " Andorra",
  "codi": "12578",
  "cp": " Santa Coloma "},
 {"Comarca": " Vall\xc3\xa8s Occidental",
  "Departament": "Sabadell. Servei d'Informaci\xc3\xb3 de Mediaci\xc3\xb3 en el Centre de Mediaci\xc3\xb3 Comunit\xc3\xa0ria",
  "Depen": "",
  "Nom": "",
  "Poblacio": "Sabadell ",
  "codi": "17062",
  "cp": ""},
 {"Comarca": None,
  "Departament": "Secci\xc3\xb3 de Secretaria dels Serveis Territorials a les Terres de l'Ebre",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18236",
  "cp": None},
 {"Comarca": " Alemanya",
  "Departament": "Secretaria de la Delegaci\xc3\xb3 del Govern de la Generalitat de Catalunya a Alemanya",
  "Depen": "",
  "Nom": "",
  "Poblacio": "Berl\xc3\xadn ",
  "codi": "16552",
  "cp": " "},
 {"Comarca": " Regne Unit",
  "Departament": "Secretaria de la Delegaci\xc3\xb3 del Govern de la Generalitat de Catalunya al Regne Unit",
  "Depen": "",
  "Nom": "",
  "Poblacio": " Londres",
  "codi": "16550",
  "cp": "EC4Y 1AA"},
 {"Comarca": " Maresme",
  "Departament": "Servei Comarcal de Catal\xc3\xa0 del Maresme (SCC)",
  "Depen": "Matar\xc3\xb3 ",
  "Nom": "",
  "Poblacio": None,
  "codi": "8262",
  "cp": ""},
 {"Comarca": " Maresme",
  "Departament": "Servei Local de Catal\xc3\xa0 de Matar\xc3\xb3 (SLC)",
  "Depen": "Matar\xc3\xb3 ",
  "Nom": "",
  "Poblacio": None,
  "codi": "6878",
  "cp": ""},
 {"Comarca": " Tarragona ",
  "Departament": "Serveis Territorials de Salut a Tarragona",
  "Depen": "",
  "Nom": "Josep Mercad\xc3\xa9 i Orriols",
  "Poblacio": "",
  "codi": "2902",
  "cp": "43002"},
 {"Comarca": " Andorra",
  "Departament": "Serveis Tur\xc3\xadstics SA",
  "Depen": "",
  "Nom": "",
  "Poblacio": " Andorra la Vella",
  "codi": "11587",
  "cp": "AD500 "},
 {"Comarca": None,
  "Departament": "Serveis d'Orientaci\xc3\xb3 Jur\xc3\xaddica (SOJ)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "15490",
  "cp": None},
 {"Comarca": None,
  "Departament": "Serveis d'informaci\xc3\xb3 mediadora (SIM)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17056",
  "cp": None},
 {"Comarca": None,
  "Departament": "Serveis d'orientaci\xc3\xb3 mediadora (SOM)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17027",
  "cp": None},
 {"Comarca": None,
  "Departament": "Subdirecci\xc3\xb3 General de Coordinaci\xc3\xb3 i Gesti\xc3\xb3 de Programes",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18214",
  "cp": None},
 {"Comarca": None,
  "Departament": "Tel\xc3\xa8fon L\xc3\xadnea Verda Drogodepend\xc3\xa8ncies",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "17195",
  "cp": None},
 {"Comarca": None,
  "Departament": "Tel\xc3\xa8fon d'Emerg\xc3\xa8ncies 112",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "10606",
  "cp": None},
 {"Comarca": None,
  "Departament": "Tel\xc3\xa8fon de Consulta del Consumidor",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "5821",
  "cp": None},
 {"Comarca": None,
  "Departament": "Tel\xc3\xa8fon de la SIDA",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "3390",
  "cp": None},
 {"Comarca": None,
  "Departament": "Tel\xc3\xa8fon del Dia de l'Oient (Catalunya M\xc3\xbasica)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "7734",
  "cp": None},
 {"Comarca": None,
  "Departament": "Tel\xc3\xa8fon del Programa d'Atenci\xc3\xb3 Postadoptiva",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "14566",
  "cp": None},
 {"Comarca": " Barcelona ",
  "Departament": "T\xc3\x9cV Rheinland Ib\xc3\xa9rica Inspection, Certification &amp",
  "Depen": "",
  "Nom": "Horst-Eduard Lilienthal",
  "Poblacio": "",
  "codi": "5789",
  "cp": "08006 "},
 {"Comarca": None,
  "Departament": "Unitat Especialitzada de Tecnologies de la Informaci\xc3\xb3 i les Comunicacions de l'\xc3\x80mbit Policial",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18824",
  "cp": None},
 {"Comarca": None,
  "Departament": "Unitat T\xc3\xa8cnica a Barcelona",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "10421",
  "cp": None},
 {"Comarca": None,
  "Departament": "Unitat T\xc3\xa8cnica a Girona",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "10422",
  "cp": None},
 {"Comarca": None,
  "Departament": "Unitat T\xc3\xa8cnica a Lleida",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "10423",
  "cp": None},
 {"Comarca": None,
  "Departament": "Unitat T\xc3\xa8cnica a Tarragona",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "10424",
  "cp": None},
 {"Comarca": None,
  "Departament": "Unitat de Coordinaci\xc3\xb3 Tecnicoadministrativa",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18246",
  "cp": None},
 {"Comarca": None,
  "Departament": "Unitat de Gesti\xc3\xb3 de Tercer Cicle (UGTC) (UPC)",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "14557",
  "cp": None},
 {"Comarca": None,
  "Departament": "\xc3\x80rea T\xc3\xa8cnica",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18245",
  "cp": None},
 {"Comarca": None,
  "Departament": "\xc3\x80rea d'An\xc3\xa0lisi, Planificaci\xc3\xb3 i Avaluaci\xc3\xb3 de les pol\xc3\xadtiques esportives de la Generalitat",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18102",
  "cp": None},
 {"Comarca": None,
  "Departament": "\xc3\x80rea del Sistema d'Informaci\xc3\xb3 Social",
  "Depen": None,
  "Nom": "",
  "Poblacio": None,
  "codi": "18235",
  "cp": None}]
